import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ weight: ["400", "500", "700"], subsets: ["latin"], display: "swap", variable: "--font-rubik" });

export const metadata: Metadata = {
  title: "Interactive Comments Section",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} bg-very-light-gray min-h-screen w-full antialiased`}>{children}</body>
    </html>
  );
}
