import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ weight: ["400", "500", "700"], subsets: ["latin"], display: "swap", variable: "--font-rubik" });

export const metadata: Metadata = {
  title: "Interactive Comments Section",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} relative min-h-full w-full bg-very-light-gray font-rubik antialiased`}>{children}</body>
    </html>
  );
}
